Adds support to behaviours to block when the Agent message queue is empty
grei-ufc/pade pull request #50
Opened 2020-06-26 17:19 UTC by italocampos

This PR presents the code to solve the problem of behaviours blocking described in the _issue_ #39 .

- Uses the threading.Event class;
- Depends on the PR #47;

2020-07-08 14:10 UTC, filipesaraiva requested changes

2020-07-08 14:10 UTC, filipesaraiva commented on pade/behaviours/types.py
> +        self.agent.message_event.wait()
Nice!

JADE has an other `block` version using a numeric parameter to suspend the thread for some time. Could you provide that version too?

2020-07-08 16:29 UTC, filipesaraiva commented on pade/behaviours/types.py
> +        self.agent.message_event.wait()
After the conflict resolution the lines were changed, but the feature addition is required yet.

2020-07-08 17:24 UTC, italocampos commented on pade/behaviours/types.py
> +        self.agent.message_event.wait()
There is already a method to do that. The method name is `wait(timeout)`, placed in the `BaseBehaviour` class. I'm renaming it into `block(timeout)`, however, this alteration will break some examples that use the `wait(timeout)` method.

2020-07-10 20:45 UTC, filipesaraiva approved these changes

2020-07-10 20:45 UTC, merged